### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [miyu/OpenMOBA#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by miyu** [comment]
Feel free to treat it as GPLv3 at commit 40b9c6e1bfa5ee84f30885c5ac394d3c812c12f5. I'll probably relax that to something permissive like MIT/BSD/Apache eventually.

There are a few dependencies for my other personal projects, which are probably MIT/BSD or Apache.
